language: cpp
dist: trusty

env:
  global:
    - secure: "Hju6MXSpDUWn8KcdJycu0DkzeL8lsZ4+nbNLgh/S1hFVvOjDyJR0JX0+c6MSdVK/38DZ79SEbBBDOmB6RBnBAi68kNSU+Z6enZo/xfW7q6MFjYERhXVe2XudzlG5kL7PVlpFki7y8hgOtAp57J6f0ZbSiZG4uLXUe+ruJeRXQ44="

addons:
  coverity_scan:
    project:
      name: "andreldm/kissplayer"
    notification_email: andre42m@gmail.com
    build_command_prepend: ./configure; make clean"
    build_command:   "make -j 4"
    branch_pattern: coverity_scan

before_install:
  - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
  - echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
  - sudo apt-get update -qq
  - sudo apt-get install -y libtag1-dev libfltk1.3-dev libsqlite3-dev libpng12-dev zlib1g-dev libcurl4-openssl-dev libxpm-dev libxtst-dev libxft-dev libxinerama-dev libsigc++-2.0-dev
  - wget https://www.dropbox.com/s/0z62kk2p79gs6bh/fmodapi44458linux.tar.gz?dl=1 -O fmod.tar.gz
  - mkdir fmod
  - tar xf fmod.tar.gz -C fmod --strip-components 1
  - sudo mkdir /usr/local/include/fmodex
  - sudo mv fmod/api/inc/* /usr/local/include/fmodex
  - sudo mv fmod/api/lib/*.so /usr/local/lib

before_script:
  - ./autogen.sh

script:
  - ./configure
  - make
